### ISSUE TITLE
Error: Unable to resolve module react-native-elements

### ISSUE THREAD

**Issue by topkat** [react-native-elements/vscode-extension#4]
Hi,

it seems te snippet uses`react-native-elements` instead of `@rneui/themed`. 

[This SO answers at the question](https://stackoverflow.com/questions/62209589/cannot-find-module-react-native-elements) are all about installing `react-native-elements`, but I hesitate to install the package since I don't want concurrent installations to run in parallel.

Am I missing something ?

PS: Thanks for such a clean and robust library ❤️

**Comment by top-kat** [comment]
By the way some suggestions are not exactly accurate with recent version

<img width="205" alt="image" src="https://user-images.githubusercontent.com/17770809/192100484-31c5a170-69c4-42c1-b05f-5695bf9c5c64.png">
